Add scrollbar to read eol banner
RedHatSatellite/foreman_theme_satellite pull request #25
Opened 2023-12-06 14:37 UTC by MariaAga

Text was cut in the middle and could not be read before, now users can scroll the long text on small srceens.
![Screenshot from 2023-12-06 15-34-36](https://github.com/RedHatSatellite/foreman_theme_satellite/assets/30431079/2264954c-0581-4957-b381-730314575398)

2023-12-11 14:59 UTC, kmalyjur requested changes

2023-12-11 14:59 UTC, kmalyjur commented on app/assets/stylesheets/foreman_theme_satellite/theme.scss
> +  overflow-x:scroll;
I'd suggest changing it like this so that the scrollbar isn't there if it doesn't have to. Other than that, it works great!

```suggestion
  overflow-x: auto;
```

2023-12-12 09:27 UTC, MariaAga commented on app/assets/stylesheets/foreman_theme_satellite/theme.scss
> +  overflow-x:scroll;
Thanks, that makes more sense

2023-12-12 10:11 UTC, kmalyjur approved these changes

2023-12-12 12:41 UTC, evgeni approved these changes

2023-12-12 12:41 UTC, merged