Test documentation links against a TOC file
RedHatSatellite/foreman_theme_satellite pull request #31
Opened 2024-01-11 11:21 UTC by ShimShtein

Instead of testing against the production documentation, test against a TOC file that can be generated from non-published documentation.

2024-01-11 16:57 UTC, ekohl commented on lib/tasks/foreman_theme_satellite_tasks.rake
> +    end
```suggestion
    failed = all_links.filter { |_key, doc_address| !doc_address.include?('html') && checker.test_link(doc_address) }
```

2024-01-14 15:08 UTC, ShimShtein commented
@ekohl Done, thanks!

2024-01-17 08:43 UTC, evgeni commented
Where and how will be obtain (and host) the TOC file for the upcoming release and then execute this as part of the regular CI?
My concern is that with todays setup we have "test links for N+1 release against prod N docs" which works in 80% of the cases, while with the current state of this PR we effectively move to "test links on demand by some magic process" (as the TOC file is not in the PR) thus possibly missing things when a PR does change the link but CI doesn't turn red.

Also, what about GA'ed versions, should we there also test against a TOC, even tho we *do* have published docs to test against?

2024-01-17 10:23 UTC, ShimShtein commented
> Where and how will be obtain (and host) the TOC file for the upcoming release and then execute this as part of the regular CI?

In my vision this will become a github action that we will be able to trigger on changes to either docs repo or theme repo.
The task should look like this:

1. Make sure we have ruby and asciidoctor are installed
2. Clone the theme repo
3. Clone the documentation repo
4. In the documentation repo run make task that generates the TOC file
5. In the theme repo, run the rake task

The make task that generates TOC for upstream docs lives here: https://github.com/theforeman/foreman-documentation/pull/2665. There is also a similar downstream PR that makes sure the downstream TOC is generated.

I would vote against storing the TOC file somewhere since it's cheap to generate, although we can add it as a build artifact.

Even though we _can_ test against the GA'd docs, I suggest to reuse the same procedure. It is a matter of which git tag to check out on the docs repo clone, so I don't think it's a big difference.

One of the advantages of this procedure, is the ability to test anchors validity (we didn't have it with the old tests by default).

2024-01-17 10:25 UTC, evgeni commented
How do we get GitHub to access the downstream docs repo?

2024-01-17 10:48 UTC, ShimShtein commented
Unfortunately for downstream, we will have to do it from the downstream side, unless there will be a decision to give access to the TOC file at least from upstream.

This task accepts a filename_to_link file that we can beef up and use for translating upstream names in the TOC to downstream names (or translate downstream links to their upstream counterparts). This would give us the ability to test downstream links against the upstream documentation. This will not give us full confidence for topics specific to downstream, but at least for common ones - it will do the trick.

2024-01-17 11:02 UTC, evgeni commented
This smells like a source for regressions then (= when a PR to *this* repo can't verify the links automatically).

2024-02-20 09:55 UTC, ShimShtein commented
Added TOC file to the fixtures directory. The file would be updated by automatic PRs.

2024-03-01 09:21 UTC, evgeni commented on lib/foreman_theme_satellite/documentation.rb
> +      [/docs\.theforeman\.org\/.*?\/Managing_Hosts\/.*?registering-a-host.*?managing-hosts/i, "#{ForemanThemeSatellite.documentation_root}/managing_hosts/registering_hosts_to_server_managing-hosts#Re
the same link exists in `DOCS_GUIDES_LINKS` but wasn't updated?

2024-03-01 09:22 UTC, evgeni commented on lib/tasks/foreman_theme_satellite_tasks.rake
> +    all_links = ForemanThemeSatellite::Documentation::USER_GUIDE_DICTIONARY
you should also collect `ForemanThemeSatellite::Documentation::DOCS_GUIDES_LINKS` :)

2024-03-01 09:23 UTC, evgeni requested changes
ForemanThemeSatellite::Documentation::DOCS_GUIDES_LINKS is untested

2024-03-03 12:58 UTC, ShimShtein commented
Added DOCS_GUIDES_LINKS hash too

2024-04-01 12:22 UTC, ShimShtein commented on lib/tasks/foreman_theme_satellite_tasks.rake
> +    all_links = ForemanThemeSatellite::Documentation::USER_GUIDE_DICTIONARY
Found the error. Now it's fixed and the tests work as expected

2024-04-01 13:00 UTC, ShimShtein commented
I don't think the test failures are related. Ready for another round

2024-04-15 11:37 UTC, evgeni commented on test/link_checker.rb
> +    %r{/html/(.*)}.match(path)&.[](1)
```suggestion
    %r{/html/(.*)}.match(path).to_a[1]
```

that's the same, right? I was starring at that `&.[]` too long.

2024-04-15 11:42 UTC, evgeni commented on test/link_checker.rb
> +    rest = split&.[](2)
```suggestion
    first, rest = path.split('/', 2)
```

2024-04-15 11:51 UTC, evgeni commented on test/link_checker.rb
> +    rest = split&.[](2)
```
% cat /tmp/bench.rb 
require 'benchmark/ips'

path = "something/very/long/but/we/dont/care"

Benchmark.ips do |x|
  x.report("regex") do
    split = path.match(%r{([^/]*)/(.*)})
    first = split&.[](1) || path
    rest = split&.[](2)
  end

  x.report("split") do
    first, rest = path.split('/', 2)
  end
end
```

```
% ruby /tmp/bench.rb   
Warming up --------------------------------------
               regex   145.613k i/100ms
               split   315.618k i/100ms
Calculating -------------------------------------
               regex      1.423M (± 1.3%) i/s -      7.135M in   5.014002s
               split      3.064M (± 0.7%) i/s -     15.465M in   5.047714s
```

;-)

2024-04-15 11:59 UTC, evgeni commented on lib/foreman_theme_satellite/documentation.rb
> +        'registering-a-host_managing-hosts' => "#{ForemanThemeSatellite.documentation_root}/managing_hosts/registering_hosts_to_server_managing-hosts#Registering_Hosts_by_Using_Global_Registration_ma
the `test_docs_redirect_branded` is related, as you changed the link here.

2024-04-15 12:00 UTC, evgeni requested changes
see inline comments.

ack once resolved

2024-04-18 17:05 UTC, evgeni approved these changes

2024-04-18 17:05 UTC, merged